package com.dabomstew.pkrandom.gui;

import com.dabomstew.pkrandom.pokemon.GenRestrictions;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;

import java.awt.*;
import java.util.Locale;

/**
 * 
 * @author Stewart
 */
public class GenerationLimitDialog extends javax.swing.JDialog {

    /**
     * 
     */
    private static final long serialVersionUID = 106783506965080925L;
    private boolean pressedOk;

    /**
     * Creates new form GenerationLimitDialog
     */
    public GenerationLimitDialog(RandomizerGUI parent, GenRestrictions current, int generation) {
        super(parent, true);
        initComponents();
        initialState(generation);
        if (current != null) {
            current.limitToGen(generation);
            restoreFrom(current);
        }
        enableAndDisableBoxes();
        pressedOk = false;
        setLocationRelativeTo(parent);
        setVisible(true);

    }

    public boolean pressedOK() {
        return pressedOk;
    }

    public GenRestrictions getChoice() {
        GenRestrictions gr = new GenRestrictions();
        gr.setAllow_gen(1, this.gen1CB.isSelected());
        gr.setAllow_gen(2, this.gen2CB.isSelected());
        gr.setAllow_gen(3, this.gen3CB.isSelected());
        gr.setAllow_gen(4, this.gen4CB.isSelected());
        gr.setAllow_gen(5, this.gen5CB.isSelected());
        gr.setAllow_gen(6, this.gen6CB.isSelected());
        gr.setAllow_gen(7, this.gen7CB.isSelected());
        gr.setAllow_gen(8, this.gen8CB.isSelected());
        gr.setAllow_gen(9, this.gen9CB.isSelected());


        return gr;
    }

    private void initialState(int generation) {
        if (generation < 2) {
            gen2CB.setVisible(false);
        }
        if (generation < 3) {
            gen3CB.setVisible(false);
        }
        if (generation < 4) {
            gen4CB.setVisible(false);
        }
        if (generation < 5) {
            gen5CB.setVisible(false);
        }
        if (generation < 6) {
            gen6CB.setVisible(false);
        }
        if (generation < 7) {
            gen7CB.setVisible(false);
        }
        if (generation < 8) {
            gen8CB.setVisible(false);
        }
        if (generation < 9) {
            gen9CB.setVisible(false);
        }
    }

    private void restoreFrom(GenRestrictions restrict) {
        gen1CB.setSelected(restrict.isAllow_gen(1));
        gen2CB.setSelected(restrict.isAllow_gen(2));
        gen3CB.setSelected(restrict.isAllow_gen(3));
        gen4CB.setSelected(restrict.isAllow_gen(4));
        gen5CB.setSelected(restrict.isAllow_gen(5));
        gen6CB.setSelected(restrict.isAllow_gen(6));
        gen7CB.setSelected(restrict.isAllow_gen(7));
        gen8CB.setSelected(restrict.isAllow_gen(8));
        gen9CB.setSelected(restrict.isAllow_gen(9));
    }

    /* @formatter:off */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        includePokemonHeader = new javax.swing.JLabel();
        gen1CB = new javax.swing.JCheckBox();
        gen2CB = new javax.swing.JCheckBox();
        gen3CB = new javax.swing.JCheckBox();
        gen4CB = new javax.swing.JCheckBox();
        gen5CB = new javax.swing.JCheckBox();
        gen6CB = new javax.swing.JCheckBox();
        gen7CB = new javax.swing.JCheckBox();
        gen8CB = new javax.swing.JCheckBox();
        gen9CB = new javax.swing.JCheckBox();
        relatedPokemonHeader = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        warningRomHackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle", Locale.ROOT); // NOI18N
        setTitle(bundle.getString("GenerationLimitDialog.title")); // NOI18N

        includePokemonHeader.setFont(new java.awt.Font(FlatRobotoFont.FAMILY, Font.BOLD, 12)); // NOI18N
        includePokemonHeader.setText(bundle.getString("GenerationLimitDialog.includePokemonHeader.text")); // NOI18N

        gen1CB.setText(bundle.getString("GenerationLimitDialog.gen1CB.text")); // NOI18N
        gen1CB.addActionListener(this::gen1CBActionPerformed);

        gen2CB.setText(bundle.getString("GenerationLimitDialog.gen2CB.text")); // NOI18N
        gen2CB.addActionListener(this::gen2CBActionPerformed);

        gen3CB.setText(bundle.getString("GenerationLimitDialog.gen3CB.text")); // NOI18N
        gen3CB.addActionListener(this::gen3CBActionPerformed);

        gen4CB.setText(bundle.getString("GenerationLimitDialog.gen4CB.text")); // NOI18N
        gen4CB.addActionListener(this::gen4CBActionPerformed);

        gen5CB.setText(bundle.getString("GenerationLimitDialog.gen5CB.text")); // NOI18N
        gen5CB.addActionListener(this::gen5CBActionPerformed);

        gen6CB.setText(bundle.getString("GenerationLimitDialog.gen6CB.text")); // NOI18N
        gen6CB.addActionListener(this::gen6CBActionPerformed);

        gen7CB.setText(bundle.getString("GenerationLimitDialog.gen7CB.text")); // NOI18N
        gen7CB.addActionListener(this::gen7CBActionPerformed);

        gen8CB.setText(bundle.getString("GenerationLimitDialog.gen8CB.text")); // NOI18N
        gen8CB.addActionListener(this::gen8CBActionPerformed);

        gen9CB.setText(bundle.getString("GenerationLimitDialog.gen9CB.text")); // NOI18N
        gen9CB.addActionListener(this::gen9CBActionPerformed);

        relatedPokemonHeader.setFont(new java.awt.Font(FlatRobotoFont.FAMILY, Font.BOLD, 12)); // NOI18N
        relatedPokemonHeader.setText(bundle.getString("GenerationLimitDialog.relatedPokemonHeader.text")); // NOI18N
        relatedPokemonHeader.setVisible(false);

        okButton.setText(bundle.getString("GenerationLimitDialog.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("GenerationLimitDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        warningRomHackLabel.setFont(new java.awt.Font(FlatRobotoFont.FAMILY, Font.BOLD, 12)); // NOI18N
        warningRomHackLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningRomHackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningRomHackLabel.setText(bundle.getString("GenerationLimitDialog.warningRomHackLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gen9CB)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(includePokemonHeader)
                                                        .addComponent(gen1CB)
                                                        .addComponent(gen2CB)
                                                        .addComponent(gen3CB)
                                                        .addComponent(gen4CB)
                                                        .addComponent(gen5CB)
                                                        .addComponent(gen6CB)
                                                        .addComponent(gen7CB)
                                                        .addComponent(gen8CB))
                                                .addGap(106, 106, 106)
                                                // Add relatedPokemonHeader here in the horizontal group
                                                .addComponent(relatedPokemonHeader))) // Add relatedPokemonHeader to horizontal layout
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addGap(32, 32, 32)
                                .addComponent(cancelButton)
                                .addGap(134, 134, 134))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(warningRomHackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(includePokemonHeader)
                                        .addComponent(relatedPokemonHeader)) // Already present in vertical layout
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen1CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen2CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen3CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen4CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen5CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen6CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen7CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen8CB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gen9CB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okButton)
                                        .addComponent(cancelButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warningRomHackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enableAndDisableBoxes() {

        /* Nothing to do anymore */

    }

    private void gen1CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen1CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen1CBActionPerformed

    private void gen2CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen2CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen2CBActionPerformed

    private void gen3CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen3CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen3CBActionPerformed

    private void gen4CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen4CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen4CBActionPerformed

    private void gen5CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen5CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen5CBActionPerformed

    private void gen6CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen6CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen6CBActionPerformed

    private void gen7CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen7CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen7CBActionPerformed

    private void gen8CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen8CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen8CBActionPerformed

    private void gen9CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gen9CBActionPerformed
        enableAndDisableBoxes();
    }// GEN-LAST:event_gen9CBActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
        pressedOk=true;
        setVisible(false);
    }// GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        pressedOk=false;
        setVisible(false);
    }// GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox gen1CB;
    private javax.swing.JCheckBox gen2CB;
    private javax.swing.JCheckBox gen3CB;
    private javax.swing.JCheckBox gen4CB;
    private javax.swing.JCheckBox gen5CB;
    private javax.swing.JCheckBox gen6CB;
    private javax.swing.JCheckBox gen7CB;
    private javax.swing.JCheckBox gen8CB;
    private javax.swing.JCheckBox gen9CB;
    private javax.swing.JLabel includePokemonHeader;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel relatedPokemonHeader;
    private javax.swing.JLabel warningRomHackLabel;
    // End of variables declaration//GEN-END:variables
    /* @formatter:on */
}
